import React from 'react';
import { isMobileOnly } from 'react-device-detect';
import Grid from '@material-ui/core/Grid';
import Link from '@material-ui/core/Link';
import Typography from '@material-ui/core/Typography';
import { gradientTextStyle, defaultTheme } from '../../styles';

export default function AboutTab(props) {
  return (
    <Grid
      container
      direction="column"
      style={{alignItems:'center'}}
    >
      <Grid item>
        <Typography
          variant="h1"
          style={{
            fontWeight:'bold',
            fontFamily:'Shadows Into Light',
            ...gradientTextStyle
          }}
        >
          About
        </Typography>
      </Grid>
      <Grid item style={{padding: isMobileOnly ? '10px 20px 100px 20px' : '30px'}}>
        <Typography style={{fontFamily:'Raleway', fontSize: isMobileOnly ? '20px' : '22px'}}>
        RecipeBook is an online collection of recipes supplied by food enthusiasts wishing to share their creations with the world. Anyone with a desire to expand their culinary skills or simply decide what to make for dinner will find value in this digital hub of ideas. The content is generated by the exchange of recipes among users, especially those who enjoy making food and want to explore new things to cook. Creating an account is free and simple; once registered, you can follow other users and post your own recipes. Visit the <Link href="#" style={{color: defaultTheme.palette.primary.main}} onClick={props.visitSignup}>Sign Up</Link> page to get started!
        </Typography>
      </Grid>
    </Grid>
  );
}