export const FETCH_RECIPE_REQUESTED = 'FETCH_RECIPE_REQUESTED';
export const FETCH_RECIPE_SUCCEEDED = 'FETCH_RECIPE_SUCCEEDED';
export const FETCH_RECIPE_FAILED = 'FETCH_RECIPE_FAILED';
export const SET_ACTIVE_RECIPE = 'SET_ACTIVE_RECIPE';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const ADD_VIEWED_RECIPE = 'ADD_VIEWED_RECIPE';
export const TOGGLE_SPINNER_VISIBILITY = 'TOGGLE_SPINNER_VISIBILITY';